name: Python RSS to JSON project scan
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install pytest, coverage and other modules
        run: |
          python -m pip install --upgrade pip
          pip install unittest-xml-reporting pytest coverage requests feedparser argparse
      - name: Run unit tests execution report
        run: python tests/rss_json_test.py
      - name: Run coverage with pytest
        run: coverage run -m pytest
      - name: Run coverage to generate XML
        run: coverage xml
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
